### ISSUE TITLE
All hooks always time out?

### ISSUE THREAD

**Issue by TotempaaltJ** [apiaryio/dredd-hooks-python#32]
```python
import dredd_hooks as hooks


@hooks.before_all
def hook(transaction):
    print('this will time out')
```
Prints `info: Hooks handler stdout: this will time out`, sits for a while, and then claims that "Hook handling timed out."

Any idea what might be happening here?

**Comment by w-vi** [comment]
Strange behaviour ... what python version are you using?

**Comment by TotempaaltJ** [comment]
I'm using Python 3.6 with Dredd 3.2.0, with dredd_hooks 0.1.2

**Comment by w-vi** [comment]
Thanks a lot. We are not currently testing against Python 3.6 so that might be the problem, let me investigate.

**Comment by honzajavorek** [comment]
@TotempaaltJ Tests seem to pass for Python 3.6. Could you provide more info? How does your API description look like? Could you share at least an anonymized example of it (which hangs as well)?

**Comment by TotempaaltJ** [comment]
The tests don't work on my machine either! This is getting more interesting...

The "Message exchange for event afterAll", "Message exchange for event beforeAll", and "Message exchange for event afterEach" scenarios fail with a similar output:

```
  Scenario: Message exchange for event afterEach                        # features/tcp_server.feature:32
      Killing server...
      Killing handler...
    Given I run `dredd-hooks-python` interactively                      # aruba-0.6.2/lib/aruba/cucumber.rb:113
    When I wait for output to contain "Starting"                        # aruba-0.6.2/lib/aruba/cucumber.rb:131
      execution expired (Timeout::Error)
      features/tcp_server.feature:34:in `When I wait for output to contain "Starting"'
    And I connect to the server                                         # features/step_definitions/dredd_steps.rb:18
    And I send a JSON message to the socket:                            # features/step_definitions/dredd_steps.rb:22
      """
      {"event": "afterEach", "uuid": "3234-abcd", "data": {"key":"value"}}
      """
    And I send a newline character as a message delimiter to the socket # features/step_definitions/dredd_steps.rb:27
    Then I should receive same response                                 # features/step_definitions/dredd_steps.rb:31
    And I should be able to gracefully disconnect                       # features/step_definitions/dredd_steps.rb:40
```

**Comment by TotempaaltJ** [comment]
Oh, and it seems to work with only the `@hooks.before('...')` and `@hooks.after('...')` hooks. I'll see if I can add an `afterEach` and if it'll break then.

**Comment by TotempaaltJ** [comment]
Now it's just this one that's failing:

```
  Scenario: Message exchange for event afterAll                         # features/tcp_server.feature:56
      Killing server...
      Killing handler...
    Given I run `dredd-hooks-python` interactively                      # aruba-0.6.2/lib/aruba/cucumber.rb:113
    When I wait for output to contain "Starting"                        # aruba-0.6.2/lib/aruba/cucumber.rb:131
      execution expired (Timeout::Error)
      features/tcp_server.feature:58:in `When I wait for output to contain "Starting"'
    And I connect to the server                                         # features/step_definitions/dredd_steps.rb:18
    And I send a JSON message to the socket:                            # features/step_definitions/dredd_steps.rb:22
      """
      {"event": "afterAll", "uuid": "5234-abcd", "data": {"key":"value"}}
      """
    And I send a newline character as a message delimiter to the socket # features/step_definitions/dredd_steps.rb:27
    Then I should receive same response                                 # features/step_definitions/dredd_steps.rb:31
    And I should be able to gracefully disconnect                       # features/step_definitions/dredd_steps.rb:40
```

**Comment by TotempaaltJ** [comment]
`dredd --level silly` returns this:

```
debug: Running hooks...
verbose: Sending HTTP transaction data to hooks handler: 64fb4411-79d7-4566-ad22-f7d6cfafb110
debug: TCP communication with hooks handler errored. Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:285:12)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/hooks-worker-client.js:324:31
    at TransactionRunner.runHook (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:280:9)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:161:28
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1007:9
    at replenish (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:881:17)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:885:9
    at _asyncMap (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1005:5)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1091:16
    at timeLimit (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:4785:3)
    at Object.timesSeries (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:917:16)
    at TransactionRunner.runHooksForData (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:185:20)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:108:30
    at TransactionRunner.executeTransaction (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:520:14)
    at TransactionRunner.executeTransaction (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:3:57)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:103:28
    at TransactionRunner.runHooksForData (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:189:14)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:99:26
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:186:16
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1012:9
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:359:16
    at replenish (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:876:25)
    at iterateeCallback (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:866:17)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:843:16
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1009:13
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:166:24
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:281:18
    at Timeout.handleTimeout [as _onTimeout] (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/hooks-worker-client.js:352:20)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)

debug: TCP communication with hooks handler errored. Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:285:12)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/hooks-worker-client.js:325:31
    at TransactionRunner.runHook (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:280:9)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:161:28
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1007:9
    at replenish (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:881:17)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:885:9
    at _asyncMap (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1005:5)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1091:16
    at timeLimit (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:4785:3)
    at Object.timesSeries (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:917:16)
    at TransactionRunner.runHooksForData (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:185:20)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:108:30
    at TransactionRunner.executeTransaction (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:520:14)
    at TransactionRunner.executeTransaction (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:3:57)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:103:28
    at TransactionRunner.runHooksForData (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:189:14)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:99:26
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:186:16
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1012:9
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:359:16
    at replenish (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:876:25)
    at iterateeCallback (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:866:17)
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:843:16
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/node_modules/async/dist/async.js:1009:13
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:166:24
    at /Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/transaction-runner.js:281:18
    at Timeout.handleTimeout [as _onTimeout] (/Users/martijn/.nvm/versions/node/v6.3.1/lib/node_modules/dredd/lib/hooks-worker-client.js:352:20)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)

warn: Hook handling timed out.
```

**Comment by TotempaaltJ** [comment]
My code was throwing an exception which wasn't being properly bubbled up. #34 fixes this 💃
